version: '3.3'
services:
  db:
    container_name: database
    restart: always
    ports:
      - 5432:5432
    #network_mode: "host"
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  web:
    container_name: server
    build: .
    command: python manage.py runserver 0.0.0.0:80
      #python manage.py app
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
  bot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python manage.py app
    restart: always
