version: '3.3'
services:
  db:
    container_name: database
    ports:
      - 5432:5432
    #network_mode: "host"
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always

  web:
    container_name: server
    build: .
    command: python manage.py runserver 0.0.0.0:80
      #python manage.py app
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  bot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python manage.py app
    restart: always

  celery:
    container_name: celery
    build: .
    command: celery -A adminka worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A adminka beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
